### ISSUE TITLE
Models/Controllers for Volunteer and Adoption forms

### ISSUE THREAD

**Issue by bam1056** [ADKebert/petrescue#2]
Howdy Alan/Adam-

Can we get the ability to submit the data from the Adoption and Volunteer forms to the server so we can store each Volunteer and potential adopter? An adopter would simply need fields for First Name, Last Name, email, phone number and let's just say a comment where they can add an aditional bit of information they want to include about their adoption desires. The same for a volunteer except they need an additional field for the type of volunteer work they are wanting to do

**Comment by ADKebert** [comment]
From Brett's Slack message:
desired fields for volunteer: fname, lname, phone, email, activity
desired fields for adopter: fname, lname, phone, email
